name: Continuous Integration

on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
         dotnet-version: 5.0.400
      
    - name: Restore
      run: dotnet restore src/TempMailAPI.sln
      
    - name: Build
      run: dotnet build src/TempMailAPI.sln --configuration Release --no-restore
      
    - name: Pack
      run: dotnet pack src/TempMailAPI/TempMailAPI.csproj --output nuget-packages --configuration Release
    
    - name: Publish
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

