name: Continuous Integration

on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Restore
      run: dotnet restore src/TempMailAPI.sln
      
    - name: Build
      run: dotnet build src/TempMailAPI.sln --configuration Release --no-restore
      
    - name: Publish
      run: dotnet nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
