name: Run Tests

on:
  workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
         dotnet-version: 6.0.x
      
    - name: Restore
      run: dotnet restore src/TempMail.csproj
      
    - name: Build
      run: dotnet build src/TempMail.sln --configuration Release --no-restore

    - name: Test
      env:
        TM_API_URI: ${{ secrets.NUGET_API_KEY }}
        TM_LOGIN: ${{ secrets.TM_LOGIN }}
        TM_PASSWORD: ${{ secrets.TM_PASSWORD }}
        TM_SMTP_FROM: ${{ secrets.TM_SMTP_FROM }}
        TM_SMTP_HOST: ${{ secrets.TM_SMTP_HOST }}
        TM_SMTP_LOGIN: ${{ secrets.TM_SMTP_LOGIN }}
        TM_SMTP_PASSWORD: ${{ secrets.TM_SMTP_PASSWORD }}
        TM_SMTP_PORT: ${{ secrets.TM_SMTP_PORT }}       
      run: dotnet test src/TempMail/TempMail.Tests.csproj --no-restore --verbosity normal
